### ISSUE TITLE
Border Router is not using storage for Thread

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/nanostack-border-router#104]
The Thread stack learns the network settings from the commissioning process and saves them to RAM memory. Therefore, the learned network settings are lost when you restart the device next time.

To prevent re-commissioning, it should be possible to save the Thread configuration settings to an SD card. This is supported in Mesh minimal app.
https://github.com/ARMmbed/mbed-os-example-mesh-minimal

However, the Border Router is not using any storage for this.

**Comment by MarceloSalazar** [comment]
Internal reference: IOTTHD-2558

**Comment by SeppoTakalo** [comment]
This would introduce external dependency.
Mbed OS does not yet support SD driver or storage selector.

**Comment by MarceloSalazar** [comment]
The BR application can handle another dependency, similarly to the mesh-minimal app.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2559

**Comment by artokin** [comment]
README updated to contain chapter about file system in PR: https://github.com/ARMmbed/nanostack-border-router/pull/117. Closing this issue.
