### ISSUE TITLE
Failed to build Thread Border Router with IAR toolchain

### ISSUE THREAD

**Issue by artokin** [ARMmbed/nanostack-border-router#109]
Thread build with IAR toolchain are failing with the following error:

Link: nanostack-border-router

Error[Lp015]: section placement failure: overcommitted content in
          [0x20000000-0x20027fff]

[ERROR] Error[Lp015]: section placement failure: overcommitted content in
          [0x20000000-0x20027fff]

[mbed] ERROR: "/usr/bin/python" returned error code 1.

[mbed] ERROR: Command "/usr/bin/python -u /builds/ws/rder-router_PR-108-XRRBN26HSGCL52SJFJ2ATFT3TPWRV/nanostack-border-router/mbed-os/tools/make.py -t IAR -m K64F --source . --build out/THREAD/K64F/IAR/ --app-config ./configs/Thread_Atmel_RF.json" in "/builds/ws/rder-router_PR-108-XRRBN26HSGCL52SJFJ2ATFT3TPWRV/nanostack-border-router"

**Comment by kjbracey-arm** [comment]
Note that we can only get away with this because this app removed from mbed OS PR morph builds during 5.9 merge.

**Comment by SeppoTakalo** [comment]
Study whether `mbed-mesh-api.use-malloc-for-heap` can be used to fix this.
https://os-doc-builder.test.mbed.com/docs/development/reference/configuration-mesh.html

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2590

**Comment by artokin** [comment]
PR https://github.com/ARMmbed/nanostack-border-router/pull/110 is using `mbed-mesh-api.use-malloc-for-heap` and it seems to work OK. 

That PR will also change EMAC back to ETH due some stability/memory issues. It will break NUCLEO_F429ZI builds.

**Comment by artokin** [comment]
PR https://github.com/ARMmbed/nanostack-border-router/pull/110 merged to mbed-os-5.9.0-oob branch. Thread commissioning tested manually with these changes and mbed-os-example-mesh-minimal.
Closing issue. A new issue will be created for failing NUCLEO_F429ZI builds.
