### ISSUE TITLE
MBED_CONF_APP_THREAD_SECURITY_POLICY not defined in mbed_app.json.

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/nanostack-border-router#111]
Shouldn't the line
https://github.com/ARMmbed/nanostack-border-router/blob/bbeea301453b6479d4b755e345167f1c2d1337f0/source/borderrouter_thread_tasklet.c#L203
actually be
```
    link_configuration->securityPolicy = MBED_CONF_MBED_MESH_API_THREAD_SECURITY_POLICY;
```
?

@karsev

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2591

**Comment by karsev** [comment]
The nanostack-border-router does not have dependencies to the mesh-api configuration.
See https://github.com/ARMmbed/nanostack-border-router/blob/master/configs/Thread_Atmel_RF.json for how security policy is defined ( "thread-security-policy": 255).
We will consider using mesh-api in the future releases.

**Comment by markus-becker-tridonic-com** [comment]
Still, it's confusing to have two config variables where only one of them gets used.
