### ISSUE TITLE
Thread commission fails when Border Router is built with using IAR or ARMC6

### ISSUE THREAD

**Issue by artokin** [ARMmbed/nanostack-border-router#114]
Thread commissioning fails when Border Router is build with IAR or ARMC6 compiler. Commissioning works fine when builds are made by using ARM or GCC_ARM.

Commissioning device (mobile phone) does not enter to screen where QR-code can be scanned. Therefore I'm not able to add new devices to the network.

Tests were made against mbed-os-5.9.0-oob branch.

**Comment by adbridge** [comment]
@artokin ARMC6 is not officially supported yet. Does it work with ARMC5 ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2595

**Comment by artokin** [comment]
This is working fine witn ARMC5 and GCC__ARM. It looks like the problem exists only with IAR/ARMC6. 
I was using IAR ANSI C/C++ Compiler V7.80.1.28/LNX for ARM (from CI) and IAR Workbench 8.11.2

**Comment by artokin** [comment]
PR https://github.com/ARMmbed/nanostack-border-router/pull/116 will adjust mbedtls MBEDTLS_SSL_MAX_CONTENT_LEN size to 4096 (from 16k).  Then IAR BR commissioning works as memory allocation succeeds.

**Comment by artokin** [comment]
PR merged to mbed-os-5.9.0-oob branch. 
Issue with ARMC6 commissioning still remains but as ARMC6 is not officially supported no further actions will be made. 
Closing this issue.
