### ISSUE TITLE
Target HOME_GATEWAY_6LOWPAN

### ISSUE THREAD

**Issue by Juiggy** [ARMmbed/nanostack-border-router#130]
I have a L-Tek [Home Gateway 6LowPan](https://os.mbed.com/platforms/HOME-GATEWAY-6LOWPAN/) and I want to make it my border router, connected to a router via ethernet.

Can I use Nanostack Border Router for this? What target should I use to compile my program?

Thank you in advance

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2681

**Comment by artokin** [comment]
This repository allows you to build border router to K64F or NUCLEO_F429ZI boards. Unfortunately there is no support for HOME GATEWAY 6LOWPAN.
