### ISSUE TITLE
Thread commissioner

### ISSUE THREAD

**Issue by vervaekejonathan** [ARMmbed/nanostack-border-router#136]
Does the border router (with Thread activated) automatically create a thread network and is able to accept joiners (when using a thread configuration)?
What do I have to do to connect devices that want to join?
Thanks!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2804

**Comment by artokin** [comment]
Hello @vervaekejonathan ,

The Thread border router is able to create its own network and it is able to accept new devices to the network when they are commissioned using commissioning application (currently running on [Android](https://play.google.com/store/apps/details?id=org.threadgroup.commissioner)) You can use [mesh-minimal application](https://github.com/ARMmbed/mbed-os-example-mesh-minimal) as a joiner (by default mesh-minimal application is able to connect to nanostack-border-router as they both share the same network configuration).

Here you can find more detailed documentation about Thread networking: https://os.mbed.com/docs/v5.9/reference/mesh-tech.html#introduction-to-thread-networking-stack. Also Thread commissioning is explained there. 

Best regards,
Arto

**Comment by artokin** [comment]
Closing, new issue with Thread commissioning created to: https://github.com/ARMmbed/nanostack-border-router/issues/137
