### ISSUE TITLE
nanostack-border-router hard faults when building with debug profile

### ISSUE THREAD

**Issue by jarlamsa** [ARMmbed/nanostack-border-router#140]
Border router hard faults when building with --profile debug

Used hardware: K64F with Atmel radio
Used SW:
nanostack-border-router : master
mbed-os: 5.10.0

Steps to reproduce
clone nanostack-border-router
mbed deploy
mbed compile -m K64F -t GCC_ARM --app-config configs/Thread_Atmel-RF.json

flash and run

Result:
++ MbedOS Fault Handler ++

FaultType: HardFault

Context:
R0   : 00000725
R1   : 00000000
R2   : FFFFFFFF
R3   : 0000300A
R4   : 2001F9C9
R5   : 00100023
R6   : 00000000
R7   : 00000000
R8   : 00000000
R9   : 00000000
R10  : 00000000
R11  : 00000000
R12  : 00095E3D
SP   : 20001638
LR   : 00005CA9
PC   : 2001F9D6
xPSR : 210F0000
PSP  : 200015D0
MSP  : 2002FFA8
CPUID: 410FC241
HFSR : 40000000
MMFSR: 00000000
BFSR : 00000004
UFSR : 00000000
DFSR : 00000008
AFSR : 00000000
Mode : Thread
Priv : Privileged
Stack: PSP

-- MbedOS Fault Handler --

++ MbedOS Error Info ++
Error Status: 0x80FF013D Code: 317 Module: 255
Error Message: Fault exception
Location: 0x94BA1
Error Value: 0x2001F9D6
Current Thread: Id: 0x20001788 Entry: 0x997DD StackSize: 0x400 StackMem: 0x20001310 SP: 0x2002FEF8
For more info, visit: https://armmbed.github.io/mbedos-error/?error=0x80FF013D
-- MbedOS Error Info --

**Comment by artokin** [comment]
This issue if fixed by #147, closing issue.
