### ISSUE TITLE
Error while compiling using mbed-cli/online compiler: "fsl_enet.h: No such file or directory"

### ISSUE THREAD

**Issue by psppalash** [ARMmbed/nanostack-border-router#159]
Trying to compile nanostack border router for KW41Z board.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-3286

**Comment by artokin** [comment]
Fixed in https://github.com/ARMmbed/nanostack-border-router/pull/161.
Now the application can be compiled to KW41Z using online compiler.
