### ISSUE TITLE
issues with s2lp with test cases in test_apps directory

### ISSUE THREAD

**Issue by abhi227** [ARMmbed/nanostack-border-router#174]
[log1-no-vv.txt](https://github.com/ARMmbed/nanostack-border-router/files/3232327/log1-no-vv.txt)
[log1-vv.txt](https://github.com/ARMmbed/nanostack-border-router/files/3232328/log1-vv.txt)

I am running or atleast trying to run NANOSTACK test cases from **"TEST_APPS"** directory in mbed-os folder. Hardware configuration is as defined -
1. PLATFORM: NUCLEO_F429ZI
2. RF DRIVER: S2LP [(X-NUCLEO-S2868A1) and (STEVAL-FKI868V1)] 

total 3 nucleo's-f429 are being utilized along with a x-nucleo-s2868a1 and 2 units of steval-fki868v1.

am facing multiple issues and listing them here one by one

1. Issues with adding S2LP driver for built-in nanostack test cases.
  
I modified mbed_app.json under device folder 
  d:\mbed-os\TEST_APPS\device\nanostack_mac_tester\mbed_app.json
  with following
            "atmel-rf.provide-default": false,
            "s2lp.provide-default": true
but still during test phase I am facing issues with compilation and nanostack test binaries are always skipped but socket binaries are created.

**Issues 2:** 

socket tests are indeed passing but not in automatic mode, out of two duts utilised one always tends to timeout after passing first case. leaving final verdict with 
1. TCPSERVER_ACCEPT being PASSED
2. and rest of associated cases FAIL 

HOWEVER, all of the above socket test pass if I run them individually 
 
[log1-vv.txt](https://github.com/ARMmbed/nanostack-border-router/files/3232328/log1-vv.txt)
[log1-no-vv.txt](https://github.com/ARMmbed/nanostack-border-router/files/3232327/log1-no-vv.txt)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-3567

**Comment by artokin** [comment]
Hi,

Would you please check the `--test-config` value according to instructions in https://github.com/ARMmbed/mbed-os/tree/master/TEST_APPS/device/nanostack_mac_tester? If I remember correctly the ´--test-config´ should point to https://github.com/ARMmbed/mbed-os/blob/master/tools/test_configs/NanostackMACTester.json

Would you please try again with updated config?

Best Regards,
Arto

**Comment by abhi227** [comment]
its same

> Would you please check the --test-config value according to instructions in https://github.com/ARMmbed/mbed-os/tree/master/TEST_APPS/device/nanostack_mac_tester? If I remember correctly the ´--test-config´ should point to https://github.com/ARMmbed/mbed-os/blob/master/tools/test_configs/NanostackMACTester.json

its same

**Comment by JuhPuur** [comment]
Adding
`"atmel-rf.provide-default": false,`
`"s2lp.provide-default": true`
to tools/test_configs/NanostackMACTester.json and running
`mbed test --compile --icetea -t GCC_ARM -m NUCLEO_F429ZI -DICETEA_MAC_TESTER_ENABLED --test-config NANOSTACK_MAC_TESTER`
produced a build success for me.

**Comment by mikter** [comment]
This is quite old issue if this is still valid and requires changes please reopen
