### ISSUE TITLE
Compilation errors for a port of the Thread on a EFR32MG12 device

### ISSUE THREAD

**Issue by keepitsimplejim** [ARMmbed/nanostack-border-router#230]
I'm trying to get the Thread wireless radio working for a custom port for the EFR32MG12 BRD4162A and the problem that I'm having is with the NanostackRfPhyEfr32 stack not compiling due to the build errors below.

The custom port is copied from the already supported TB_SENSE_12 device with custom device_peripherals.h, PeripheralPins.c & PinNames.h.
I'm using the mbed command line tool version 1.10.2 is used to build the device, with the gcc-arm-none-eabi-9-2019-q4-major as the cross compiler.

I've been able to reproduce this error for the TB_SENSE_12 as shown below.

I've tried to work out why the compiler is raising the error of the 'get_mac_address' and 'rf_register' being a non-class type by comparing it to the MCR20 nano stack implementation but the definitions are the same.

I would be grateful if you could point me in the right direction so I could solve this.

Thanks,
Chris

$ mbed compile -m TB_SENSE_12 -t GCC_ARM
[mbed] Working path "nanostack-border-router" (program)
Building project nanostack-border-router (TB_SENSE_12, GCC_ARM)
Scan: nanostack-border-router
Compile [  0.1%]: SPIRIT_Commands.c
Compile [  0.2%]: SPIRIT_Aes.c
Compile [  0.3%]: PeripheralPins.c
Compile [  0.4%]: SPIRIT_Calibration.c
Compile [  0.6%]: SPIRIT_Csma.c
Compile [  0.7%]: SPIRIT_DirectRF.c
Compile [  0.8%]: SPIRIT_General.c
Compile [  0.9%]: SPIRIT_LinearFifo.c
Compile [  1.0%]: SPIRIT_Irq.c
Compile [  1.1%]: SPIRIT_Gpio.c
Compile [  1.2%]: SPIRIT_Management.c
Compile [  1.3%]: SPIRIT_PktBasic.c
Compile [  1.4%]: SPIRIT_PktMbus.c
Compile [  1.6%]: SPIRIT_PktCommon.c
Compile [  1.7%]: SPIRIT_PktStack.c
Compile [  1.8%]: SPIRIT_Qi.c
Compile [  1.9%]: SPIRIT_Types.c
Compile [  2.0%]: mbed_tz_context.c
Compile [  2.1%]: SPIRIT_Timer.c
Compile [  2.2%]: rf_wrapper.cpp
[Error] rf_wrapper.cpp@40,19: request for member 'rf_register' in 'rf_phy', which is of non-class type 'NanostackRfPhyEfr32()'
[Error] rf_wrapper.cpp@45,12: request for member 'get_mac_address' in 'rf_phy', which is of non-class type 'NanostackRfPhyEfr32()'
[ERROR] In file included from ./mbed-os/targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/em_device.h:72,
                 from ./mbed-os/targets/TARGET_Silicon_Labs/TARGET_EFM32/emlib/inc/em_cmu.h:33,
                 from ./mbed-os/targets/TARGET_Silicon_Labs/TARGET_EFM32/common/clocking.h:27,
                 from ./mbed-os/targets/TARGET_Silicon_Labs/mbed_rtx.h:21,
                 from ./mbed-os/rtos/source/TARGET_CORTEX/mbed_rtx_conf.h:26,
                 from ./mbed-os/rtos/source/TARGET_CORTEX/mbed_rtx_storage.h:31,
                 from ./mbed-os/rtos/mbed_rtos_storage.h:22,
                 from ./mbed-os/rtos/rtos.h:27,
                 from ./mbed-os/mbed.h:22,
                 from ./mbed-os/features/nanostack/nanostack-interface/targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/NanostackRfPhyEfr32.h:20,
                 from ./drivers/rf_wrapper.cpp:34:
./mbed-os/targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/efr32mg12p332f1024gl125.h:130: warning: "__FPU_PRESENT" redefined
  130 | #define __FPU_PRESENT             1U /**< Presence of FPU  */
      | 
<command-line>: note: this is the location of the previous definition
./drivers/rf_wrapper.cpp: In function 'int8_t rf_device_register()':
./drivers/rf_wrapper.cpp:40:19: error: request for member 'rf_register' in 'rf_phy', which is of non-class type 'NanostackRfPhyEfr32()'
   40 |     return rf_phy.rf_register();
      |                   ^~~~~~~~~~~
./drivers/rf_wrapper.cpp: In function 'void rf_read_mac_address(uint8_t*)':
./drivers/rf_wrapper.cpp:45:12: error: request for member 'get_mac_address' in 'rf_phy', which is of non-class type 'NanostackRfPhyEfr32()'
   45 |     rf_phy.get_mac_address(mac);
      |            ^~~~~~~~~~~~~~~

[mbed] ERROR: "/usr/bin/python3" returned error.
       Code: 1
       Path: "nanostack-border-router"
       Command: "/usr/bin/python3 -u nanostack-border-router/mbed-os/tools/make.py -t GCC_ARM -m TB_SENSE_12 --source . --build ./BUILD/TB_SENSE_12/GCC_ARM"
       Tip: You could retry the last command with "-v" flag for verbose output

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-4221

**Comment by keepitsimplejim** [comment]
Has there been any progress on this problem?

**Comment by JarkkoPaso** [comment]
Hi Chris,
Did you add new radio type to drivers/rf_wrapper.cpp? If so, can you share those changes?

**Comment by keepitsimplejim** [comment]
Yes I did, find attached the corresponding change is rf_wrapper.cpp and mbed_app.json
[rf_wrapper.cpp.txt](https://github.com/ARMmbed/nanostack-border-router/files/4988500/rf_wrapper.cpp.txt)
[mbed_app.json.txt](https://github.com/ARMmbed/nanostack-border-router/files/4988505/mbed_app.json.txt)

**Comment by JarkkoPaso** [comment]
Thanks, can you try if it compiles without parentheses in rf_phy, like this:
NanostackRfPhyEfr32 rf_phy;

**Comment by keepitsimplejim** [comment]
Thank you that was it.
