### ISSUE TITLE
border router memory footprint

### ISSUE THREAD

**Issue by kwangeom** [ARMmbed/nanostack-border-router#233]
Hi,

I have a question on footprint of nanostack border router.
I have built "ws_border_router" using IAR.
From  https://os.mbed.com/docs/mbed-os/v6.1/apis/configuration-mesh.html,   
its memory footprint should be around 261kB.
But mine has this big number even with full optimization level.

  545'758 bytes of readonly  code memory
   81'062 bytes of readonly  data memory
  161'934 bytes of readwrite data memory

Anybody can explain why?

Regards,

Kwang

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-4251

**Comment by artokin** [comment]
Hi Kwang,

The figures in https://os.mbed.com/docs/mbed-os/v6.1/apis/configuration-mesh.html indicate only code size of the nanostack files (mesh stack). Those figures do not include Mbed OS platform, drivers or anything else. 

Typically nanostack-border-router application binary size is roughly 400-700 kB depending on the configuration options used. 

Best regards,
Arto
