### ISSUE TITLE
how to skip the authentication and key install

### ISSUE THREAD

**Issue by kwangeom** [ARMmbed/nanostack-border-router#234]
Hello,

Just for development purpose, is there any way to disable authentication and key install(PMK, PTK, etc) to skip those steps in bootstrap?

Regards,

Kwang

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-4263

**Comment by mikter** [comment]
There is no implementation to skip authentication. There should be no need for it as you can get the key and see captures in Wireshark I you want. Also it would remove quite important part in testing.
