### ISSUE TITLE
using 6LoWPAN border router on an IPv4 based ISP 

### ISSUE THREAD

**Issue by clem-ent** [ARMmbed/nanostack-border-router#27]
Hi,

I have a problem to configure the Border router on an IPv4 network with an IPv6 tunnel.
I already tried the client exemple and its working with the Firefly border-router on an **IPV6 network**

To do it on an IPV4 network I created a tunnel with https://tunnelbroker.net/, and I configured my raspberry PI with this tunnel. The tunnel seems to work as i can ping ipv6.google.com on the raspberryPi.
After I installed RADVD with this tuto : [here](https://devzone.nordicsemi.com/blogs/729/create-hurricane-tunnel-broker-on-raspberry-pi/), in the step 4, I have used the 64bit prefix

For the border router, I used a K64F with atmel shield : 
I turned off the dynamic bootstrap
`"backhaul-dynamic-bootstrap": false,`
`"backhaul-prefix: "2001:470:****:***::",`
`"backhaul-default-route": 2001:470:****:***::1/64",`
`"backhaul-next-hop": 2001:470:****:***::2/64",`

The backhaul prefix is the same as in file radvd.conf
The default route is the IP address of the ethernet port on Raspberry Pi
The next-hop is the IP address of the tunnel IPv6

But in this case i'm not able to send HTTP request while it was working on the ipv6 network.

Have you an idea why ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3049

**Comment by clem-ent** [comment]
I solved the problem, I put the dynamic bootstrap in dynamic mode (`true`)
