### ISSUE TITLE
RF interface addresses

### ISSUE THREAD

**Issue by devran01** [ARMmbed/nanostack-border-router#32]
The global/ULA address for the Thread interface is not printed into the debug logs when the Thread bootstrap is completed.

```
[INFO][brro]: Thread bootstrap ready
[INFO][brro]: RF interface addresses:
[INFO][brro]:  [0] fe80::39ff:afcd:33e8:1029
[INFO][brro]:  [1] fd00:db8::f428:4d76:b48:9efb
[INFO][brro]:  [2] fd00:db8::ff:fe00:0
[INFO][brro]:  [3] fd00:db8::ff:fe00:fc00
```

Calling the method `print_interface_addr(thread_br_conn_handler_thread_interface_id_get());` in a cyclic task prints the global/ULA address of the thread interface.

```
[INFO][app ]:  [0] fe80::39ff:afcd:33e8:1029
[INFO][app ]:  [1] fd00:db8::f428:4d76:b48:9efb
[INFO][app ]:  [2] fd00:db8::ff:fe00:0
[INFO][app ]:  [3] fd00:db8::ff:fe00:fc00
[INFO][app ]:  [4] fd00:db8::ff:fe00:fc01
[INFO][app ]:  [5] fd00:db80::39ff:afcd:33e8:1029
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3072

**Comment by SeppoTakalo** [comment]
CC: @mikter @artokin Please check.

**Comment by mikter** [comment]
There is no periodic address printing in application, but I don't know if that is the best place to have this? is this a requirement that you would like us to do? at least this could be temporary solution.

Thread does not get Global address at boot up, but the address is given by border router when it becomes available. It can also be removed and the local Thread connectivity is still working.

Should we have proper interface which informs the application that global address status has changed. There is address registration mechanism available in address.c which could be used to send event to application when global address is changed.
@kjbracey-arm want to give any input on this?

**Comment by kjbracey-arm** [comment]
I would expect the system to show newly-added addresses at trace level "info" - if info trace is for anything, it's for that.

The address core probably doesn't say anything, maybe it should. At the minute it is up to the bootstrap, and I guess Thread deems its bootstrap to be complete once the Thread is up?

Hmm, no, I've checked, and you should get "Address added to IF 1: xxxx" from the core, at INFO level.

As to API, yes, I'm sure that might be useful to some, but we're mainly talking about testing here, aren't we? So printing is probably easier for those users.

There probably should be an address print API, like the routing print API, but there isn't at the moment. You can infer the address by looking at the route print, and seeing the Loopback entries, but that's a bit hacky.

**Comment by devran01** [comment]
@mikter Having a periodic function to print the addresses configured on an interface will NOT be useful as it will print the same addresses unless there is a change. I did it to check if there was a global address configured on the Thread interface.

I agree with @kjbracey-arm regarding the API implementation. I'm happy as long as the address configured on an interface is known to the user.

@kjbracey-arm I'm using nanostack-border-router with Nanostack binary.
I don't see the message "Address added to IF 1: xxxx" in the debug logs.
```[INFO][app ]: Starting NanoStack Border Router...
[INFO][app ]: Build date: May 23 2017 08:42:39
[INFO][brro]: NET_IPV6_BOOTSTRAP_AUTONOMOUS
[INFO][app ]: Using SLIP backhaul driver...
[DBG ][slip]: SLIP driver id: 1

[DBG ][brro]: Backhaul driver ID: 1
[DBG ][brro]: Create Mesh Interface
[INFO][brro]: thread_if_id: 1
[INFO][brro]: thread_interface_up
[INFO][brro]: PAN ID 700
[INFO][brro]: RF channel 16
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: service tasklet init
[DBG ][coap]: Coap random msg ID: 50910
[DBG ][ThSA]: Service 1, Uri registration uri: a/nd
[DBG ][ThSA]: service init interface 1, port 49191, options 130
[DBG ][ThSA]: Service 2, Uri registration uri: c/tx
[DBG ][ThSA]: Service 2, Uri registration uri: c/cs
[DBG ][ThSA]: Service 2, Uri registration uri: c/cg
[DBG ][ThSA]: Service 2, Uri registration uri: c/cp
[DBG ][ThSA]: Service 2, Uri registration uri: c/ca
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: Service 3, Uri registration uri: c/mg
[DBG ][ThSA]: Service 3, Uri registration uri: c/ag
[DBG ][ThSA]: Service 3, Uri registration uri: c/pg
[DBG ][ThSA]: Service 3, Uri registration uri: c/cg
[DBG ][ThSA]: Service 3, Uri registration uri: c/pq
[DBG ][ThSA]: Service 3, Uri registration uri: c/es
[DBG ][ThSA]: Service 3, Uri registration uri: c/ab
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: Service 4, Uri registration uri: d/dg
[DBG ][ThSA]: Service 4, Uri registration uri: d/dr
[DBG ][ThSA]: Service 4, Uri registration uri: d/dq
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[INFO][brro]: mesh0 bootstrap ongoing...
[DBG ][brro]: backhaul_interface_up: 1

[DBG ][brro]: Backhaul interface ID: 2
[DBG ][brro]: Backhaul bootstrap started
[DBG ][ThSA]: service tasklet initialised
[DBG ][nnvm]: ns_nvm_data_read() key=com.arm.nanostack.thread.static_link_cfg, len=120, ctx=0x2000e858
[DBG ][rnvm]: platform_nvm_read() com.arm.nanostack.thread.static_link_cfg len=120
[DBG ][slip]: slip_if_tx(): datalen = 72
[DBG ][slip]: slip_if_tx(): datalen = 64
[DBG ][slip]: slip_if_tx(): datalen = 56
[DBG ][slip]: slip_if_tx(): datalen = 72
[DBG ][slip]: slip_if_tx(): datalen = 64
[INFO][brro]: BR interface_id: 2
[INFO][TBRH]: Ethernet (eth0) bootstrap ready. IP: fd00:db80::4db4:9e30:c851:6321
[INFO][brro]: Backhaul interface addresses:
[INFO][brro]:  [0] fe80::dc42:77ff:fe15:1abd
[INFO][brro]:  [1] fd00:db80::4db4:9e30:c851:6321
[DBG ][TBRH]: Eth0 connection status: 1
[DBG ][TBRH]: mesh0 is down
[DBG ][ThSA]: Service 3, Uri registration uri: a/as
[DBG ][ThSA]: Service 3, Uri registration uri: a/ar
[DBG ][ThSA]: Service 3, Uri registration uri: c/lp
[DBG ][ThSA]: Service 3, Uri registration uri: c/la
[DBG ][ThSA]: Service 3, Uri registration uri: a/sd
[DBG ][ThSA]: Service 3, Uri registration uri: c/as
[DBG ][ThSA]: Service 3, Uri registration uri: c/ps
[DBG ][ThSA]: Service 3, Uri registration uri: c/cs
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: Service 6, Uri registration uri: a/aq
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: Service 7, Uri registration uri: a/an
[DBG ][ThSA]: Service 7, Uri registration uri: a/ae
[INFO][brro]: Thread bootstrap ready
[INFO][brro]: RF interface addresses:
[INFO][brro]:  [0] fe80::bd3c:d9d2:1754:a941
[INFO][brro]:  [1] fd00:db8::a03b:693:9660:3c6c
[INFO][brro]:  [2] fd00:db8::ff:fe00:0
[INFO][brro]:  [3] fd00:db8::ff:fe00:fc00
[DBG ][TBRH]: mesh0 connection status: 1
[DBG ][TBRH]: DHCP server started 
[DBG ][CoSA]: Service 5, send CoAP request payload_len 20
[DBG ][coap]: sn_coap_builder_calc_needed_packet_data_size_2
[DBG ][coap]: sn_coap_protocol_build - payload len 20
[DBG ][coap]: sn_coap_builder_2
[DBG ][coap]: sn_coap_builder_calc_needed_packet_data_size_2
[DBG ][coap]: sn_coap_builder_2 - message len: [36]
[DBG ][coap]: sn_coap_protocol_build - msg id: [50910], bytes: [36]
[DBG ][ThSA]: Service 5, CoAP TX Function - mid: 50910
[DBG ][TBRH]: Updated fd00:db80::/64 prefix
[DBG ][ThSA]: service recv socket data len 36 
[DBG ][coap]: sn_coap_protocol_parse
[DBG ][CoSA]: CoAP status:0, type:0, code:2, id:50910
[DBG ][ThSA]: Service 3, call request recv cb uri a/sd
[DBG ][ThSA]: Service 3, Uri unregistration uri: c/tx
[DBG ][CoSA]: Service 3, send CoAP response
[DBG ][coap]: sn_coap_builder_calc_needed_packet_data_size_2
[DBG ][coap]: sn_coap_protocol_build - payload len 0
[DBG ][coap]: sn_coap_builder_2
[DBG ][coap]: sn_coap_builder_calc_needed_packet_data_size_2
[DBG ][coap]: sn_coap_builder_2 - message len: [10]
[DBG ][coap]: sn_coap_protocol_build - msg id: [50910], bytes: [10]
[DBG ][ThSA]: Service 3, CoAP TX Function - mid: 50910
[DBG ][ThCH]: send from source address fd:00:0d:b8:00:00:00:00:00:00:00:ff:fe:00:00:00
[DBG ][ThSA]: service recv socket data len 10 
[DBG ][coap]: sn_coap_protocol_parse
[DBG ][CoSA]: CoAP status:0, type:32, code:68, id:50910
[DBG ][CoSA]: Service 5, response received
```
However using nanostack source prints the "Address added to IF " as info.
```
[INFO][addr]: Address added to IF 1: fd00:db80::6cce:4a2:3047:491f
```

**Comment by kjbracey-arm** [comment]
Okay, I guess whichever binary you're using has trace disabled. Unfortunate.

Maybe we will end up needing some sort of event. Although you could just monitor periodically using whatever API you were using to print.

**Comment by kjbracey-arm** [comment]
We do now have the ability to exclude particular trace levels from builds - maybe better if those binaries only had DBG excluded, but keep INFO and higher.

**Comment by devran01** [comment]
+1 to keep INFO in the binaries.

**Comment by SeppoTakalo** [comment]
When you are using Nanostack binaries or sources, do you know whether they are from same git tag?

Current binaries in mbed OS master are `v6.0.1` or similar and there is PR to update them to `v6.1.0` which is 671 commits ahead. It might be that these prints have been added later.
If so, they will appear in mbed OS 5.5.

**Comment by devran01** [comment]
@SeppoTakalo Had a quick look at Nanostack v6.0.1 souce and the address.c includes code to print " Address added to IF 1:". However, as @kjbracey-arm suggested traces may be disabled in the binaries. We should enable at least the "info" traces in the released binaries.

**Comment by artokin** [comment]
PR created to trace interface addresses in application: https://github.com/ARMmbed/nanostack-border-router/pull/40

**Comment by artokin** [comment]
PR merged to master. Interface addresses printed in 20s intervals.
