### ISSUE TITLE
Give warning when on IPv4 network

### ISSUE THREAD

**Issue by AriParkkila** [ARMmbed/nanostack-border-router#43]
I connected (by mistake) nanostack-border-router to IPv4 network where it couldn't obtain IPv6 address.

Here is log from UART:
[INFO][Eth ]: Ethernet cable connected.
[INFO][addr]: Tentative Address added to IF 2: fe80::fc46:23ff:fed6:3ac0
[INFO][addr]: DAD passed on IF 2: fe80::fc46:23ff:fed6:3ac0

I think border-router should report a clear error when it does not get IPv6 address.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3106

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/sal-stack-nanostack-private/pull/1269
