### ISSUE TITLE
Seem like border router is not creating the 6lowpan netowrk

### ISSUE THREAD

**Issue by saboohajaz** [ARMmbed/nanostack-border-router#57]
Here is what i got at serial port

[INFO][brro]: PANID: 691
[INFO][brro]: NET_IPV6_BOOTSTRAP_AUTONOMOUS
[WARN][brro]: Security NOT enabled
[DBG ][core]: NS Root task Init
DBG ][core]: NS Root task Init
[0m
[DBG ][sck ]: Socket Tasklet Generated
net Task
[DBG ][SPIRIT]: rf_register (724)
[DBG ][SPIRIT]: rf_ack_loop (605)
rf_ack_loop (605)
trol (147)
[DBG ][SPIRIT]: rf_register (771)
[DBG ][brro]: RF device ID: 0
[DBG ][SPIRIT]: rf_set_mac_address (228), adr0=f0, adr1=f1, adr2=f2, adr3=f3, adr4=f4, adr5=f5, adr6=f6, adr7=f7
[DBG ][SPIRIT]: rf_set_mac_address (228), adr0=f0, adr1=f1, adr2=f2, adr3=f3, adr4=f4, adr5=f5, adr6=f6, adr7=f7
[DBG ][brro]: RF interface ID: 1
[INFO][app ]: Starting NanoStack Border Router...
[INFO][app ]: Build date: Aug 23 2017 20:23:48

it is not proceeding further
I am using SLIP Backhaul

**Comment by saboohajaz** [comment]
I am using NUCLEO_F429ZI and Spirit1

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3169

**Comment by SeppoTakalo** [comment]
Hi @saboohajaz 
Are you able to attach a debugger to this device and provide a backtrace to see where it is stuck.
I believe F429 have on-board ST-Link chip, so should be easy.

Also, can you provide me the `mbed_app.json` file that you used.

Thanks.

**Comment by saboohajaz** [comment]
Just an update.. 
I noticed perhaps there is a problem with SLIP Serial port. So i disabled RTS/CTS
#if defined(MBED_CONF_APP_SLIP_HW_FLOW_CONTROL)
    //pslipmacdriver = new SlipMACDriver(SERIAL_TX, SERIAL_RX, SERIAL_RTS, SERIAL_CTS);
	  pslipmacdriver = new SlipMACDriver(SERIAL_TX, SERIAL_RX);
#else
    pslipmacdriver = new SlipMACDriver(SERIAL_TX, SERIAL_RX);
#endif

Then i got this on serial port:

[INFO][brro]: PANID: 691                                                        
[INFO][brro]: NET_IPV6_BOOTSTRAP_AUTONOMOUS                                     
[DBG ][brro]: Using PSK security mode, key ID = 1                               
[DBG ][core]: Allocate Root Tasklet                                             
[DBG ][6lo ]: P.Init                                                            
                                                                                
[DBG ][sck ]: Socket Tasklet Generated                                          
[DBG ][SPIRIT]: rf_register (724)                                               
[DBG ][SPIRIT]: rf_register (724)                                               
[DBG ][SPIRIT]: rf_interface_state_control (147)                                
[DBG ][SPIRIT]: rf_ack_loop (605)                                               
[DBG ][SPIRIT]: rf_register (771)                                               
[DBG ][brro]: RF device ID: 0                                                   
[DBG ][SPIRIT]: rf_set_mac_address (226), adr0=f0, adr1=f1, adr2=f2, adr3=f3, ad
r4=f4, adr5=f5, adr6=f6, adr7=f7                                                
[DBG ][SPIRIT]: rf_set_mac_address (226), adr0=f0, adr1=f1, adr2=f2, adr3=f3, ad
r4=f4, adr5=f5, adr6=f6, adr7=f7                                                
[DBG ][brro]: RF interface ID: 1                                                
[INFO][app ]: Starting NanoStack Border Router...                               
[INFO][app ]: Build date: Aug 27 2017 08:00:19ÿC¡h´%Zm[90m[DBG ][brro]: Backhaul
 driver ID: 1                                                                   
[DBG ][brro]: Backhaul interface ID: 2                                          
[DBG ][ip6s]: IPV6 interface Base Ready                                         
[DBG ][rout]: Added route:                                                      
[DBG ][rout]:                    fe80::/64  if:2 src:'Static' id:0 lifetime:infi
nite                                                                            
[DBG ][rout]:      On-link (met 128)                                            
[DBG ][rout]: Added route:                                                      
[DBG ][rout]:                    ff00::/8   if:2 src:'Static' id:0 lifetime:infi
nite                                                                            
[DBG ][rout]:      On-link (met 192)                                            
[DBG ][brro]: Backhaul bootstrap started                                        
[INFO][addr]: Tentative Address added to IF 2: fe80::280:e1ff:fe22:3d           
[DBG ][addr]: LL64 Register OK!                                                 
[DBG ][slip]: slip_if_tx(): datalen = 72                                        
F [åDBGÿ" À][slip]: slip_if_tx(): datalen = 64                                  
[INFO][addr]: DAD passed on IF 2: fe80::280:e1ff:fe22:3d                        
[DBG ][ip6s]: Interface ID: 2, ipv6: fe80::280:e1ff:fe22:3d                     
[DBG ][ip6s]: DAD OK                                                            
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
[DBG ][slip]: slip_if_tx(): datalen = 72                                        
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
À`U$:ÿþ€€áÿþ"=ÿ…·n€á"=ÀDestination Cache:                                       
 ff02::2 (life 5)                                                               
     PMTU 1500 (life 0)                                                         
 ff02::1:ff22:3d (life 5)                                                       
     PMTU 1500 (life 0)                                                         
Routing table:                                                                  
                   ff00::/8   if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 192)                                                          
                   fe80::/64  if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 128)                                                          
RPL memory usage 36                                                             
RPL Domain 20017ea4                                                             
Neighbour Cache 2                                                               
Reachable Time: 44671   Retrans Timer: 1000   MTU: 1500                         
Neighbour Cache 1                                                               
Reachable Time: 15000   Retrans Timer: 1000   MTU: 1280                         
[INFO][app ]: Heap size: 49972, Reserved: 4112, Reserved max: 4928, Alloc fail: 
0                                                                               
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
À`U$:ÿþ€€áÿþ"=ÿ…·n€á"=À  

I cant upload the json configuration file here. Hence, i converted it to PDF and attached with that post.
Furthermore, I am debugging it and will post soon.. where it is stopping
[sa.pdf](https://github.com/ARMmbed/nanostack-border-router/files/1254219/sa.pdf)

**Comment by saboohajaz** [comment]
The last part I am copying again here ..
Strange .. the heap allocation failure
[INFO][app ]: Heap size: 49972, Reserved: 4112, Reserved max: 4928, Alloc fail: 
0  


Destination Cache:                                       
 ff02::2 (life 5)                                                               
     PMTU 1500 (life 0)                                                         
 ff02::1:ff22:3d (life 5)                                                       
     PMTU 1500 (life 0)                                                         
Routing table:                                                                  
                   ff00::/8   if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 192)                                                          
                   fe80::/64  if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 128)                                                          
RPL memory usage 36                                                             
RPL Domain 20017ea4                                                             
Neighbour Cache 2                                                               
Reachable Time: 44671   Retrans Timer: 1000   MTU: 1500                         
Neighbour Cache 1                                                               
Reachable Time: 15000   Retrans Timer: 1000   MTU: 1280                         
[INFO][app ]: Heap size: 49972, Reserved: 4112, Reserved max: 4928, Alloc fail: 
0                                                                               
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
À`U$:ÿþ€€áÿþ"=ÿ…·n€á"=À

**Comment by saboohajaz** [comment]
The program printing this on the serial port continuously. may be a loop

[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
À`U$:ÿþ€€áÿþ"=ÿ…·n€á"=ÀDestination Cache:                                       
 ff02::2 (life 5)                                                               
     PMTU 1500 (life 0)                                                         
 ff02::1:ff22:3d (life 4)                                                       
     PMTU 1500 (life 0)                                                         
Routing table:                                                                  
                   ff00::/8   if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 192)                                                          
                   fe80::/64  if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 128)                                                          
RPL memory usage 36                                                             
RPL Domain 20017ea4                                                             
Neighbour Cache 2                                                               
Reachable Time: 44671   Retrans Timer: 1000   MTU: 1500                         
Neighbour Cache 1                                                               
Reachable Time: 15000   Retrans Timer: 1000   MTU: 1280                         
[INFO][app ]: Heap size: 49972, Reserved: 4112, Reserved max: 4928, Alloc fail: 
0                                                                               
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
À`U$:ÿþ€€áÿþ"=ÿ…·n€á"=ÀDestination Cache:                                       
 ff02::2 (life 5)                                                               
     PMTU 1500 (life 0)                                                         
 ff02::1:ff22:3d (life 3)                                                       
     PMTU 1500 (life 0)                                                         
Routing table:                                                                  
                   ff00::/8   if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 192)                                                          
                   fe80::/64  if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 128)                                                          
RPL memory usage 36                                                             
RPL Domain 20017ea4                                                             
Neighbour Cache 2                                                               
Reachable Time: 44671   Retrans Timer: 1000   MTU: 1500                         
Neighbour Cache 1                                                               
Reachable Time: 15000   Retrans Timer: 1000   MTU: 1280                         
[INFO][app ]: Heap size: 49972, Reserved: 4112, Reserved max: 4928, Alloc fail: 
0                                                                               
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
À`U$:ÿþ€€áÿþ"=ÿ…·n€á"=ÀDestination Cache:                                       
 ff02::2 (life 5)                                                               
     PMTU 1500 (life 0)                                                         
 ff02::1:ff22:3d (life 2)                                                       
     PMTU 1500 (life 0)                                                         
Routing table:                                                                  
                   ff00::/8   if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 192)                                                          
                   fe80::/64  if:2 src:'Static' id:0 lifetime:infinite          
     On-link (met 128)                                                          
RPL memory usage 36                                                             
RPL Domain 20017ea4                                                             
Neighbour Cache 2                                                               
Reachable Time: 44671   Retrans Timer: 1000   MTU: 1500                         
Neighbour Cache 1                                                               
Reachable Time: 15000   Retrans Timer: 1000   MTU: 1280                         
[INFO][app ]: Heap size: 49972, Reserved: 4112, Reserved max: 4928, Alloc fail: 
0                                                                               
[DBG ][ip6s]: Push RS to IPV6                                                   
[DBG ][slip]: slip_if_tx(): datalen = 56                                        
À`U$:ÿþ€€áÿþ"=ÿ…·n€á"=À

**Comment by SeppoTakalo** [comment]
In the log, I can see messages like `Push RS to IPV6` so the router seems to be waiting for ICMPv6 Router Advertisements.

Do you have RADVD (Router Advertisement Daemon) running on the Linux side?
Where is your SLIP serial line connected to?

Are you aware of https://github.com/ARMmbed/mbed-access-point which is a working Linux access point that support this IPv6 SLIP.

**Comment by saboohajaz** [comment]
Yes there was a problem with slip driver.
I checked and solved it.
Thank you very much for your help

**Comment by SeppoTakalo** [comment]
Thank you for your reply.
I'll close this one.

Please open new tickets if more issues appear.
