### ISSUE TITLE
Thread Border Router hard faults with Nanostack ARM binary

### ISSUE THREAD

**Issue by artokin** [ARMmbed/nanostack-border-router#58]
Thread Border Router hard faults after startup when using:
-ARM compiler 5.06 update 3 or update 5
-Nanostack binary release

If Nanostack is compiled from sources then no hard fault is observed.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3170

**Comment by artokin** [comment]
This issue will be fixed in mbed OS 5.6.

**Comment by artokin** [comment]
Issue fixed in https://github.com/ARMmbed/mbed-os/pull/4960 that is merged to mbed OS master branch.
