### ISSUE TITLE
Stuck with SLIP border router use

### ISSUE THREAD

**Issue by ryankurte** [ARMmbed/nanostack-border-router#74]
Hey there,

I've been trying to get a SLIP border router working for a couple of days now and tbqh I am a bit stuck.
I can't seem to find any documentation or examples for the use of SLIP border routers in either autonomous (dynamic bootstrap) or static mode (ie. dhcp setup, slip attachment) It's possible I have just missed it, but, I can't see anything here, in the SLIP repo, or from wild googling.

The readme suggests "For more details on how to set the backhaul prefix and default route" to refer to documentation documentation in the private repo `https://github.com/ARMmbed/nanostack-border-router-private`.

I think I have got SLIP working with `slattach -s 115200 $SERIAL_PORT -d -p slip` and a fix to [sal-stack-nanostack-slip#11](https://github.com/ARMmbed/sal-stack-nanostack-slip/issues/11), and have tested that we have bidirectional communication by intercepting it all with `socat -x /dev/ttyUSB0,raw,echo=0,crnl PTY,link=/dev/ttyV0,raw,echo=0,crnl`, though I have yet to check if SLIP packet receipt is working on the device.

Using the standard application config from this repo I am currently:

Bringing up the `sl0` interface with:
```
echo "Setting MTU"
sudo ip link set $INTERFACE mtu 1500

echo "Allocating IP address"
sudo ip address flush sl0
sudo ip address add $ADDRESS/64 dev $INTERFACE

echo "Bringing interface up"
sudo ip link set $INTERFACE up

sudo ifconfig $INTERFACE
```

Running dnsmasq (because isc-dhcpd doesn't support SLIP) with `dnsmasq -k -C dnsmasq.conf -d -q` and the following config:
```
interface=sl0

dhcp-range=fd00::1, ra-stateless, ra-names
dhcp-option=option6:dns-server,[fd00::1]
ra-param=sl0,10,300

enable-ra
```

With bootstrap mode I can see the router solicitation (from device) and router advertisement (from dnsmasq) messages, but not convince the dhcp server to respond to solicitation requests.
In static mode I can't seem to get the pc <-> br routing working for direct connection to the br or the devices.
Hopefully it's a simple thing I've just missed, but, would appreciate any help.
(cc. @stevew817 because I think you mentioned you had something working)

Thanks,

Ryan

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2034

**Comment by devran01** [comment]
Same issue was discussed and closed in https://github.com/ARMmbed/sal-stack-nanostack-slip/issues/11
