### ISSUE TITLE
BR fails to route pings K66F + MCR20

### ISSUE THREAD

**Issue by bentcooke** [ARMmbed/nanostack-border-router#78]
The nanostack BR does not seem to be routing correctly with a static route config.  My HW setup is as follows:

1) PC connected to K66F directly via ETH
2) K66F+MCR20 shield 
3) KW24D running mesh minimal

The KW24D is connecting to the BR and pulls an IP address, but any attempts to ping this ip address (ping -6) from the PC fails.  However, I am able to ping the BR's backhaul address successfully.

The only things changed in mbed_app.json are:
radio type -> MCR20
backhaul-dynamic-bootstrap -> false

Building target = K66F

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2098

**Comment by artokin** [comment]
I got the same result when using company PC for pinging RF interface address. However, when I used test PC (no firewall) a ping to RF interface worked fine. I tested with both 6loWPAN ND and Thread configurations.

@bentcooke , would you please try with another PC?

**Comment by juhhei01** [comment]
Good point Arto. ARM firewall block IPv6 traffic that is know issue. When you are not arm intranet firewall not accept IPv6.

**Comment by juhhei01** [comment]
My old laptop was fixed to support that but I have to request that from IT and it was long journey.

**Comment by bentcooke** [comment]
@artokin and @juhhei01, thanks for the feedback and it does appear that the firewall policy was to blame.

The BR is functioning correctly with another PC that is not controlled by IT.
