### ISSUE TITLE
Support nRF52840

### ISSUE THREAD

**Issue by Cheong2K** [ARMmbed/nanostack-border-router#86]
When will this support nRF52840 with internal 802.15.4 capability? Also, how about NAT64 support?

**Comment by SeppoTakalo** [comment]
Border router is not platform specific.
It runs on Mbed OS with any Nanostack RF driver provided.

Currently Nordic have not supplied RF driver for nRF52840

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2272

**Comment by TuomoHautamaki** [comment]
Like Seppo mentioned, this application is not platform specific. 
Nordic would have to provide RF driver for nRF52840. Questions about future plans would have to go to @ARMmbed/team-nordic 
Closing this issue as there's nothing to be done for nanostack-border-router
