### ISSUE TITLE
Exporting to uvision5 with NUCLEO_F429ZI results in device not found error

### ISSUE THREAD

**Issue by kimlep01** [ARMmbed/nanostack-border-router#92]
After I export the project to uvision5 and open it, I get the following error: "Device not found, Device: STM32F429ZI". I have installed the required pack Keil.STM32F4xx_DFP.2.12.0 that the IDE suggests.

After I changed the device manually to "STM42F429ZITx" I am able to compile the example but I cannot run it in debugger due to "Internal command error". To fix this I followed the intructions found here: https://github.com/ARMmbed/mbed-os/issues/5467

* use ST-Link debugger
* Debug: connect with pre-reset

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2344

**Comment by donatieng** [comment]
+1

Seems like flash algorithms cannot be found either.

**Comment by cmonr** [comment]
It sounds like targets.json for that board needs to be updated to target that specific chip instead of using the generic core. I recall seeing PRs that would be made specifically for this.

@ARMmbed/team-st-mcd Thoughts?

**Comment by adbridge** [comment]
@theotherjimmy This looks like it should be supported. Thoughts ?

**Comment by theotherjimmy** [comment]
This is a known issue. See https://github.com/ARMmbed/mbed-os/issues/5467

**Comment by SeppoTakalo** [comment]
Closing because of duplicate issue.
