### ISSUE TITLE
6LoWPAN sub GHz mode: example client fails to register to Connector

### ISSUE THREAD

**Issue by kimlep01** [ARMmbed/nanostack-border-router#93]
After starting the border router in 6LoWPAN sub GHz mode I see the following error constantly:

[INFO][brro]: PANID: 691
[INFO][brro]: NET_IPV6_BOOTSTRAP_AUTONOMOUS
[WARN][brro]: Security NOT enabled
[INFO][app ]: Starting NanoStack Border Router...
[INFO][app ]: Build date: Mar  7 2018 18:53:25
[INFO][app ]: Using ETH backhaul driver...
[ERR ][brro]: Backhaul interface down failed
[INFO][Eth ]: Ethernet cable connected.
[INFO][addr]: Tentative Address added to IF 2: fe80::3441:b7ff:fef6:6286
[INFO][addr]: DAD passed on IF 2: fe80::3441:b7ff:fef6:6286
[INFO][addr]: Tentative Address added to IF 2: 2001:470:6af8:3000:3441:b7ff:fef6:6286
[INFO][addr]: DAD passed on IF 2: 2001:470:6af8:3000:3441:b7ff:fef6:6286
[INFO][brro]: Backhaul bootstrap ready, IPv6 = 2001:470:6af8:3000:3441:b7ff:fef6:6286
[INFO][brro]: Backhaul interface addresses:
[INFO][brro]:    [0] fe80::3441:b7ff:fef6:6286
[INFO][brro]:    [1] 2001:470:6af8:3000:3441:b7ff:fef6:6286
[INFO][brro]: RF channel: 1
[INFO][br  ]: BR nwk base ready for start
[INFO][addr]: Address added to IF 1: fe80::ff:fe00:face
[INFO][br  ]: Refresh Contexts
[INFO][br  ]: Refresh Prefixs
[INFO][addr]: Address added to IF 1: 2001:470:6af8:3000:0:ff:fe00:face
[INFO][addr]: Address added to IF 1: fe80::fec2:3d00:4:a86f
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[INFO][brro]: RF bootstrap ready, IPv6 = 2001:470:6af8:3000:0:ff:fe00:face
[INFO][brro]: RF interface addresses:
[INFO][brro]:    [0] fe80::ff:fe00:face
[INFO][brro]:    [1] fe80::fec2:3d00:4:a86f
[INFO][brro]:    [2] 2001:470:6af8:3000:0:ff:fe00:face
[INFO][brro]: 6LoWPAN Border Router Bootstrap Complete.
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0
[ERR ][AtRF]: Radio underrun is 10->40 ts d6->c2 fl 5->5 x1 0

The example client is able to connect to the 6LoWPAN network (very slowly) but fails to register to Connector. In 2.4GHz mode I didn't see any issues. Updating Atmel driver to latest master version didn't help.

Boards used as border routers: F429ZI / K66F

Border router configuration:

"rf-channel": 1,
"rf-channel-page": 2,
"rf-channel-mask": "(1<<1)",

 mbed compile -m NUCLEO_F429ZI -t IAR --app-config ./configs/6lowpan_Atmel_RF.json -c

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2345

**Comment by SeppoTakalo** [comment]
@kjbracey-arm Can you help?

What can cause this radio issue?

**Comment by SeppoTakalo** [comment]
Did one end of the communication happen to be ST based device? Is this the same issue we have seen earlier https://github.com/ARMmbed/atmel-rf-driver/issues/53

**Comment by kimlep01** [comment]
Tested with the following combinations:
F429ZI border router - K64F node
K66F border router - K64F node

**Comment by karsev** [comment]
This solved the issue -> https://github.com/ARMmbed/atmel-rf-driver/pull/66

**Comment by daniel-cesarini-tridonic-com** [comment]
@karsev what kind of tests were performed on the system to assess that the issue is *solved*? 

On our side *Tridonic* we still see the issue, or at least some issue related to the radio, also with this fix.
We are struggling to get a setup were we can get the issue to pop-up in a reproducible way, and thus are also unable to assess in a proper way whether it has been really solved.

Thank you a lot.
