### ISSUE TITLE
Linker failures when building this project

### ISSUE THREAD

**Issue by LordOfDorks** [ARMmbed/nanostack-border-router#95]
I tried to build this project but encountered errors. Any idea what may be going wrong?

Thank you
S.

Building project mbed-os (NUCLEO_F429ZI, GCC_ARM)
Scan: .
Scan: mbed
Scan: env
Scan: FEATURE_LWIP
Compile [  0.2%]: AnalogIn.cpp
    ...
[some of warnings]
    ...
Compile [100.0%]: test_env.cpp
Link: mbed-os
BUILD/NUCLEO_F429ZI/GCC_ARM/rtos/TARGET_CORTEX/mbed_boot.o: In function `__wrap_main':
C:\Users\stefanth\arm\thread\mbed-os/.\rtos\TARGET_CORTEX/mbed_boot.c:531: undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
[ERROR] BUILD/NUCLEO_F429ZI/GCC_ARM/rtos/TARGET_CORTEX/mbed_boot.o: In function `__wrap_main':
C:\Users\stefanth\arm\thread\mbed-os/.\rtos\TARGET_CORTEX/mbed_boot.c:531: undefined reference to `main'
collect2.exe: error: ld returned 1 exit status

[mbed] ERROR: "c:\python27\python.exe" returned error code 1.
[mbed] ERROR: Command "c:\python27\python.exe -u C:\Users\stefanth\arm\thread\mbed-os\tools\make.py -t GCC_ARM -m NUCLEO_F429ZI --source . --build .\BUILD\NUCLEO_F429ZI\GCC_ARM" in "C:\Users\stefanth\arm\thread\mbed-os"
---

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2393

**Comment by artokin** [comment]
Hi,

We have just updated the application to the latest Mbed-OS release. 

I tested the application by executing commands `git pull`, `mbed deploy` and `mbed compile -t GCC_ARM -m NUCLEO_F429ZI` in Windows (cmd/bash) and Ubuntu.  The builds were working fine.

Would you please try the compilation again with the latest changes? 

Here are few ideas for more information: 

- Is your environment setup like described in [handbook](https://os.mbed.com/docs/v5.8/introduction/index.html)? 

- What is the version of [mbed-cli](https://github.com/ARMmbed/mbed-cli) you are using?

Best regards,
Arto

**Comment by TuomoHautamaki** [comment]
@LordOfDorks , do you have any update based on Arto's feedback? Are you still having this issue? If not valid anymore, then please close this issue.

**Comment by artokin** [comment]
Closing the issue as no response in two weeks. Please reopen the issue if the problem still persist.
